[package]
name = "nvg-gl"
version = "0.5.0"
authors = ["sunli"]
edition = "2018"

[dependencies]
nvg = { path = ".." }
slab = "0.4.2"
gl = "0.14.0"
failure = "0.1.6"

[dev-dependencies]
glutin = "0.21.1"
